apiVersion: v1
kind: Secret
metadata:
  name: keda-aws-secrets
  namespace: keda-test
data:
  AWS_ACCESS_KEY_ID: "_INPUT_KEY_ID_"
  AWS_SECRET_ACCESS_KEY: "_INPUT_SECRET_KEY_"
--- 
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: keda-test
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID
    name: keda-aws-secrets
    key: AWS_ACCESS_KEY_ID
  - parameter: awsSecretAccessKey
    name: keda-aws-secrets
    key: AWS_SECRET_ACCESS_KEY
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: keda-test
  labels:
    test: nginx-deployment
spec:
  scaleTargetRef:
    deploymentName: nginx-deployment
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: _INPUT_QUEUE_URL_
      queueLength: "5"
      awsRegion: _INPUT_REGION_
