apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent3
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: alpine-agent3
        image: oneoneonepig/alpine-agent3
        ports:
        - containerPort: 80
