apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ifelse-chomped
data:
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  release: {{ $.Release.Name }}
  {{- end }}
  release: {{ .Release.Name }}
