apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hello-world
spec:
  selector:
    app: nginx
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
