alertmanager:
  enabled: false
alertmanagerFiles:
  alertmanager.yml: null
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
server:
  service:
    type: NodePort
  persistentVolume:
    enabled: true
    size: 30Gi
  retention: 1d # change this if you are running in production
# serverFiles:
  # alerts: ""
  # rules: ""
  # prometheus.yml: ""
