apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx
  namespace: istio-test
spec:
  host: nginx
  trafficPolicy:
    loadBalancer:
      consistentHash: 
        useSourceIp: true
