apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pre
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pre.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  restartPolicy: Never
  containers:
  {{- with .Values.pre }}
  - name: {{ .name }}
    image: {{ .image }}:{{ .imageTag }}
    command: 
    - "/bin/sleep"
    - "10"
  {{- end }}
