apiVersion: v1
kind: Service
metadata:
  name: linux-webserver
  labels:
    app: linux-webserver
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: linux-webserver
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linux-webserver
  name: linux-webserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: linux-webserver
  template:
    metadata:
      labels:
        app: linux-webserver
      name: linux-webserver
    spec:
     containers:
      - name: nginx
        image: nginx:alpine
     nodeSelector:
      kubernetes.io/os: linux
