apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-env
  labels:
    app: proxy-env
data:
  HTTPS_PROXY: "http://10.20.131.51:3128/"
  HTTP_PROXY: "http://10.20.131.51:3128/"
  NO_PROXY: "kubernetes,kubernetes.default,kubernetes.default.svc.cluster.local,10.96.0.1,127.0.0.1,localhost"
