apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: counting-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alpine
            image: alpine
            command:
            - /bin/sh
            - -c
            - for i in $(seq 1 10); do echo $i; sleep 1; done; echo "Counting completed at $(date)"
          restartPolicy: OnFailure
