apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alpine-ds
  labels:
    app: alpine-ds
spec:
  selector:
    matchLabels:
      app: alpine-ds
  template:
    metadata:
      labels:
        app: alpine-ds
    spec:
      containers:
      - name: alpine-ds
        image: alpine
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        args:
        - /bin/sh
        - -c
        - while true; do echo The pod $(POD_NAME) is on node $(NODE_NAME); sleep 10m; done
