apiVersion: batch/v1
kind: Job
metadata:
  name: counting
spec:
  template:
    spec:
      containers:
      - name: alpine
        image: alpine
        args:
        - /bin/sh
        - -c 
        - for i in $(seq 1 10); do echo $i; sleep 1; done; echo "Counting completed at $(date)"
      restartPolicy: Never
  backoffLimit: 4
