apiVersion: v1
kind: Pod
metadata:
  name: alpine-cred-file
  labels:
    app: alpine-cred-file
spec:
  containers:
  - name: alpine
    image: alpine
    args:
    - /bin/sh
    - -c
    - sleep infinity
    volumeMounts:
    - name: secret-cred
      mountPath: /var/secret
  volumes:
  - name: secret-cred
    secret:
      secretName: confidential
