apiVersion: v1
kind: Pod
metadata:
  name: alpine-data-env
  labels:
    app: alpine-data-env
spec:
  containers:
  - name: alpine
    image: alpine
    args:
    - /bin/sh
    - -c
    - sleep infinity
    env:
      - name: VAR1
        valueFrom:
          configMapKeyRef:
            name: data-env
            key: var1
      - name: VAR2
        valueFrom:
          configMapKeyRef:
            name: data-env
            key: var2
      - name: VAR3
        valueFrom:
          configMapKeyRef:
            name: data-env
            key: var3
