apiVersion: v1
kind: Pod
metadata:
  name: pod-privaterepo
  labels:
    app: pod-privaterepo
spec:
  containers:
  - name: nginx
    image: ACCOUNT_NAME/nginx
  imagePullSecrets:
  - name: myrepokey
