apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
    name: pod-with-pvc
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/tmp"
        name: tmp
  volumes:
    - name: tmp
      persistentVolumeClaim:
        claimName: mypvc
