apiVersion: v1
kind: Service
metadata:
  name: cf-dns-web
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cf-dns-web
subsets:
- addresses:
  - ip: 1.1.1.1
  ports:
  - port: 443
