apiVersion: v1
kind: Service
metadata:
  name: nginx-sts
spec:
  selector:
    app: nginx-sts
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
  labels:
    app: nginx-sts
spec:
  replicas: 1
  serviceName: nginx-sts
  selector:
    matchLabels:
      app: nginx-sts
  template:
    metadata:
      labels:
        app: nginx-sts
    spec:
      containers:
      - name: nginx-sts
        image: nginx
        ports:
        - containerPort: 80
