apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-monitor-sa
  namespace: redis
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: redis-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: redis-monitor-sa
  namespace: redis
---
#kind: ConfigMap
#apiVersion: v1
#metadata:
#  name: redis-monitor-script
#  namespace: redis
#data:
#  run.sh: |-
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-monitor
  namespace: redis
  labels:
    app: redis-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-monitor
  template:
    metadata:
      labels:
        app: redis-monitor
    spec:
      containers:
      - name: alpine
        image: alpine
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "/tmp/run.sh"]
        volumeMounts:
        - name: runsh
          mountPath: /tmp
      serviceAccountName: redis-monitor-sa
      volumes:
      - name: runsh
        configMap:
          name: redis-monitor-script
          defaultMode: 0755
